spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/springboot;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10
    username: juwon
    password: pass
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql : true
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: 'OFF'
    jdbc: 'OFF'
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.newbie.bulletinboard.domain
  type-handlers-package: com.newbie.bulletinboard.domain
  configuration:
    default-statement-timeout: 3