spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bulletinboard
    username: jinwoo
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql : true
        jdbc:
          lob:
            non_contextual_creation: true